### ISSUE TITLE
TTL validation

### ISSUE THREAD

**Issue by pavel-odintsov** [CZ-NIC/deckard#5]
Hello!

As I understand, by default deckard ignores TTL values in comparison code. But for our purposes, we need to check TTL values also. 

Is it possible to enable/disable strict TTL validation for a particular test?

Thank you!

**Comment by vcunat** [comment]
For reference, there's a test testing TTL issues by shifting time and testing *presence* of records in the answer, in `sets/resolver/iter_minmaxttl.rpl`.  (I suppose you noticed it already.)

**Comment by pavel-odintsov** [comment]
Thanks! I will check!
